<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\iPlus\Directory.Build.props" />
  <PropertyGroup>
    <TargetFramework>$(UITargetFramework)</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\bin\Debug\</OutputPath>
    <IPlusIncludeDir>..\..\iPlusMES\bin\Debug\$(UITargetFramework)</IPlusIncludeDir>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\bin\Release\</OutputPath>
    <IPlusIncludeDir>..\..\iPlusMES\bin\Release\$(UITargetFramework)</IPlusIncludeDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="gip.core.autocomponent">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(IPlusIncludeDir)\gip.core.autocomponent.dll</HintPath>
    </Reference>
    <Reference Include="gip.core.datamodel">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(IPlusIncludeDir)\gip.core.datamodel.dll</HintPath>
    </Reference>
    <Reference Include="gip.core.layoutengine">
      <HintPath>$(IPlusIncludeDir)\gip.core.layoutengine.dll</HintPath>
    </Reference>
    <Reference Include="gip.core.reporthandler">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(IPlusIncludeDir)\gip.core.reporthandler.dll</HintPath>
    </Reference>
    <Reference Include="gip.core.reporthandlerwpf">
      <HintPath>$(IPlusIncludeDir)\gip.core.reporthandlerwpf.dll</HintPath>
    </Reference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.IO.Ports" Version="9.*" />
  </ItemGroup>
</Project>